"""empty message

Revision ID: 393c93cc8d6a
Revises: 745d99c763c9
Create Date: 2020-03-04 13:52:53.216591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '393c93cc8d6a'
down_revision = '745d99c763c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_artist_id_fkey', 'Show', type_='foreignkey')
    op.create_foreign_key(None, 'Show', 'Artist', ['artist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.create_foreign_key('Show_artist_id_fkey', 'Show', 'Artist', ['artist_id'], ['id'])
    # ### end Alembic commands ###
